package com.wadpam.open.i18n.dao;


/**
 * Implementation of Business Methods related to entity Di18n.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-03-01T16:30:39.573+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class Di18nDaoBean 
	extends GeneratedDi18nDaoImpl
		implements Di18nDao 
{

}