package com.wadpam.open.i18n.dao;

/**
 * Business Methods interface for entity Di18nTranslation.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-02-25T10:25:45.264+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface Di18nTranslationDao extends GeneratedDi18nTranslationDao {

	// TODO: declare your Business Methods here
	
}
