package com.wadpam.open.i18n.dao;

/**
 * Implementation of Business Methods related to entity Di18nTranslation.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-02-25T10:25:45.264+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class Di18nTranslationDaoBean 
	extends GeneratedDi18nTranslationDaoImpl
		implements Di18nTranslationDao 
{

	// TODO: implement your Business Methods here

}
