package com.wadpam.open.i18n.dao;

/**
 * Business Methods interface for entity Di18n.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-03-01T16:30:39.573+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface Di18nDao extends GeneratedDi18nDao {

	// TODO: declare your Business Methods here
	
}
