package com.wadpam.open.tag.dao;

/**
 * Business Methods interface for entity DTag.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-03-01T11:56:39.376+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DTagDao extends GeneratedDTagDao {

	// TODO: declare your Business Methods here
	
}
