package com.wadpam.open.audit.dao;

import java.util.Collection;
import java.util.Date;

/**
 * Business Methods interface for entity DAudit.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-03-05T10:26:06.767+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DAuditDao extends GeneratedDAuditDao {

    public Long AUDIT_PARENT_ID = 1L;
    Collection<Long> whatsDeleted(Date since, Object parentKey);
}
